name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install openscad
      run: sudo apt-get install openscad

    - name: install solidpython
      run: pip install solidpython2

    - name: Generate STL files
      run: make -j $(nproc)
    
    - uses: actions/upload-artifact@v4
      with: 
        name: motostandup-STL
        path: out/*
